version: "3"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./apache:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
  php:
    image: php:7.2-fpm
    volumes:
      - ./apache:/var/www/html    
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./wordpress_data:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite    

networks:
  wpsite:
volumes:
  mysql: {}
  apache: {}
  wordpress_data: {}

#networks:
#  frontend:
#  backend:


    
#  wordpress:
#    depends_on:
#      - db
#    image: wordpress:latest
#    volumes:
#      - wordpress_data:/var/www/html
#    ports:
#      - "8000:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#  wordpress_data: {}

#____________________________________________________________________________
#version: '3'
#services:
#    apache:
#      #
#    nginx:
#      # используем последний стабильный образ nginx
#        image: nginx:latest
#        # маршрутизируем порты
#        ports:
#            - "8000:80"
#        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
#        volumes:
#            - ./hosts:/etc/nginx/conf.d
#            - ./www:/var/www
#            - ./logs:/var/log/nginx
#        # nginx должен общаться с php контейнером
#        links:
#            - php
#    php:
#        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
#        build: ./images/php
#        # этот образ будет общаться с mysql
#        links:
#            - mysql
#        # монтируем директорию с проектами
#        volumes:
#            - ./www:/var/www
#    mysql:
#        image: mariadb
#        ports:
#            - "3306:3306"
#        volumes:
#            - ./mysql:/var/lib/mysql
#        # задаем пароль для root пользователя
#        environment:
#            MYSQL_ROOT_PASSWORD: secret
#    pma:
#      # используем последний стабильный образ phpmyadmin
#        image: phpmyadmin/phpmyadmin
#        restart: always
#        links:
#            - mysql:mysql
#        ports:
#            - 8183:80
#        environment:
#            # прописываем название нашего MySQL хоста
#            PMA_HOST: mysql
#            MYSQL_USERNAME: root
#            MYSQL_ROOT_PASSWORD: secret
#